### ISSUE TITLE
Permissions system and available states from current transition

### ISSUE THREAD

**Issue by tony** [looplab/fsm#10]
``beforeEventCallback`` is a candidate for this, but checking for permissions also should encompass easy a trivial way to determine which states are accessible from the ``fsm``'s current state.

I figured ``beforeEventCallback`` could be ran iterated for events through a helper function, and that could be used to determine if an event could run without running ``Event``. But that has two downsides: we have ``Can``'s default usage won't check the callback, making it a little confusing to others who read the code (the method could infer to some all is good to proceed with the event), and in my case I want to use ``beforeEventCallback`` for other purposes.

The user could do this, perform slice operations and get to it themselves.  I'm going to experiment with how adding a preliminary callback hook / a helper method or two outside of ``Event`` to weigh if adding it is justified.

Out the door, I'm more inclined in favor of incorporating one in some form. It's possible the additional hook won't incur any penalty for those who decide not to add permission callbacks.

**Comment by maxekman** [comment]
Sounds interesting, let me know what you find out!

**Comment by tony** [comment]
I got caught up in other things since I made this issue. If I come back with something I'll re-open.

Best @maxekman
