### ISSUE TITLE
Thread safety of calls that result in transitions

### ISSUE THREAD

**Issue by kristoiv** [looplab/fsm#13]
Possible problem case: eg. reading the current state name while transitioning. There is no locking going on as far as I can see. Am I missing something?

Eg.:
``` go
fsm := NewFSM(....)
go func() {
    fmt.Println(fsm.Current())
}()
go func() {
    fsm.Event("...")
}()
```

**Comment by maxekman** [comment]
You are correct, there is no thread safety in the library yet. If you have the time I would love to accept a PR for this if it can be accomplished in a clean fashion. I can imagine it would be valuable for many users.

Otherwise I suggest using a sync.RWMutex for the whole FSM as a workaround.
