### ISSUE TITLE
No Transition error should not be handled when there is an event with same source and destination. 

### ISSUE THREAD

**Issue by smothiki** [looplab/fsm#17]
For example https://github.com/smothiki/fsm/tree/master/examples/genesis
I have the following state [machine](https://github.com/smothiki/fsm/blob/master/examples/genesis/util.go#L45-L54)  defined and want to handle an error event which tries to achieve a single state. Here while handling error event we are getting no transition error as an error from the event. A better way might be to log it as debug info rather than throwing it as an event error.

**Comment by maxekman** [comment]
Thanks for writing about your use case. In your case I would just check if the returned error is a NoTransition error to handle it separately from other errors (for example to not log it or log it differently). Logging inside a library is really bad practice and will not be added.

**Comment by nvjkmr** [comment]
Leaving this here for other folks:
```go
func (d *Door) Trigger() error {
    err := door.FSM.Event(transition)
    if _, ok := err.(fsm.NoTransitionError); ok || err == nil {
        return nil
    }
    return err
}
```
