### ISSUE TITLE
Self Transitions

### ISSUE THREAD

**Issue by theathibm** [looplab/fsm#19]
Self transitions don't seem to be supported.  The following code snippet from fsm.go seems to consider  self transitions as errors.

	if f.current == dst {
		f.afterEventCallbacks(e)
		return &NoTransitionError{e.Err}
	}

Perhaps I'm not using the fsm appropriately.  any thoughts?

**Comment by maxekman** [comment]
If you expect a self transition just check for the error. If you want to treat it as an error or not is up to you.

**Comment by maxekman** [comment]
Or did you want to do something more with a self transition? Callbacks etc.

**Comment by theathibm** [comment]
a self transition is completely valid in state machines,  FSM should really support it and not consider it an error.   Perhaps it's ok to not leave the state and then renter the same state, but the transition should still be valid and not considered and error.
![image](https://cloud.githubusercontent.com/assets/16386998/21355725/20314f0e-c69d-11e6-8551-88c4e1707d1d.png)

**Comment by maxekman** [comment]
Yes, an error could be misleading in this case, I definitely see your point. Let's discuss this further. What changes do you suggest? Does the fact that no transition happened need to be fed back into one of the callbacks or something similar?

**Comment by theathibm** [comment]
I think the transition should happen, but the leave state and then enter state may not happen since it's just a self transition.

The transition needs to be a first class citizen.   Currently beforeEvent and afterEvent hides the actual transition logic that needs to occur.

Adding one more callback called "doEvent" might be needed.

**Comment by JalfResi** [comment]
I've just been bitten by this issue. Any progress on this?

**Comment by 21stio** [comment]
This is a deterministic state machine implementation. That's why every state can only have one dst. 
There is a really simple solution tho, just add a second state machine that is created when a state is reached that has state on its own.

**Comment by maxekman** [comment]
I'll close this, referring to the last comment.

**Comment by pajacobs17** [comment]
I still think this should be looked at. The comment from @ppwfx isn't correct or I'm misunderstanding what he's saying. While the implementation of this library is based on a determinstic fsm, a determinstic fsm allows for multiple transitions out of a state _for different input_. So in my case, we have an fsm where you have to upload at least one piece of proof, but you might have to upload multiple. So it's something like:

`{Name: "upload", Src: []string{"need-upload", "uploaded"}, Dst: "uploaded"},
  {Name: "start-authorization", Src: []string{"uploaded"}, Dst: "authorization-initiated"},`

You transition to `proof-uploaded` once you have uploaded one piece, but then you *should* be able to upload multiple pieces of proof. This is why a self transition makes sense. You should still trigger the before and after functions, as the transition is still occurring.

**Comment by Ashrit263** [comment]
Hi Team, The state machine is not supporting transition from and to if its same state. There is a business requirement to allow the state transition and trigger some events in case of the from and to state is same. Any recommendation here would be appreciated
