### ISSUE TITLE
Available Transitions/Events

### ISSUE THREAD

**Issue by JalfResi** [looplab/fsm#27]
Would be cool if it was possible to query the FSM for the available transitions from the current state. Maybe an additional method that returns the valid events that would trigger the valid transitions from the current state. Thoughts?

**Comment by jamesbibby** [comment]
Plus one for this feature, I was hoping to be able to provide available transitions to my front-end so it can dynamically create action buttons.

I will put up a PR, but I don't really see an efficient way of calculating it right now.   (Seems like an O(n) solution is optimal unless a new data structure is created with the object)

**Comment by maxekman** [comment]
Fixed in #32.
