### ISSUE TITLE
Graphviz/Dot graph output of FSM

### ISSUE THREAD

**Issue by JalfResi** [looplab/fsm#28]
Generation of a dot file for the FSM would be rad.

**Comment by mrmagooey** [comment]
I made a simple dot file generator that takes `fsm.Events` as its input 

https://github.com/mrmagooey/fsmGraphviz

**Comment by maxekman** [comment]
@mrmagooey: Would you mind adding a link to you tool in the readme? It could be useful for ppl to know about. Thanks!

**Comment by mrmagooey** [comment]
I'm happy for you to add a link :+1:

**Comment by maxekman** [comment]
Btw, how does your solution differ from the one in utils? https://github.com/looplab/fsm/blob/master/utils.go

**Comment by maxekman** [comment]
I believe this is implemented.
