### ISSUE TITLE
could the dst state to be set in the event handler? 

### ISSUE THREAD

**Issue by njnuwjq** [looplab/fsm#33]
currently the dst state is set in the event defining, could it be set in the call backs, which would be much flexible?

as we just need to define a set of state, and the trigger, then we can add the change the state according to the handler result

thanks

**Comment by maxekman** [comment]
Interesting use case, can you provide a short code example here of how you would like it?

**Comment by maxekman** [comment]
Take a minute to read through this issue also: https://github.com/looplab/fsm/issues/19

**Comment by maxekman** [comment]
Closing due to no response.
