### ISSUE TITLE
Provides a v1 release

### ISSUE THREAD

**Issue by dgsb** [looplab/fsm#39]
Users of this library would need a semver v1 release of this library to ensure API stability.

**Comment by maxekman** [comment]
Grear feedback, will fix that.

**Comment by dgsb** [comment]
@maxekman any progress on that ? Thanks

**Comment by maxekman** [comment]
Can probably get to that today!

**Comment by dgsb** [comment]
great, thanks a lot

**Comment by maxekman** [comment]
Done: https://github.com/looplab/fsm/releases/tag/v0.1.0
