### ISSUE TITLE
Context in event handlers

### ISSUE THREAD

**Issue by ilyakaznacheev** [looplab/fsm#61]
It would be great to add a context to event trigger function and event handler function signature because it is required in many operations.

Probably it will require to double the methods (i.e. `fsm.EventContext(ctx, event, args...)` and `type CallbackContext func(ctx, *Event)`.

**Comment by maxekman** [comment]
Good suggestion! Will look into it when I have some time.

**Comment by ilyakaznacheev** [comment]
👏
