### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ppussar** [looplab/fsm#62]
Hi,
we are using commit 9c1f252fd079 in our software. Our renovate bot is quite unhappy with the fact that this is not a tagged release version.
Would it be possible to build a new release with the latest chanages?

Thanks in advanced!
Patrick

**Comment by maxekman** [comment]
Yes!

**Comment by maxekman** [comment]
Just released master as v0.2.0: https://github.com/looplab/fsm/releases/tag/v0.2.0
