### ISSUE TITLE
New Release ?

### ISSUE THREAD

**Issue by TheBeachMaster** [looplab/fsm#71]
A commit was introduced https://github.com/looplab/fsm/commit/01565a8066ad4bb5ed4eeb73ef88334ab01b4f85 to address a very important issue, "storing metadata" that can be consumed as one transitions between states.

However, this commit has not been published and the lib is still in `v0.2.0` . When will it be possible to have a release that ships with this feature?

**Comment by maxekman** [comment]
Thanks for pointing it out, I’ll make a new release as soon as I can (vacation atm).

**Comment by maxekman** [comment]
I have now released v0.3.0: https://github.com/looplab/fsm/releases/tag/v0.3.0
